# https://wandb.ai

# configs/logger/wandb.yaml
wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  project: "MEDIMG-src"
  entity: "nadine-flueck-hochschule-luzern"
  log_model: "all" # Saves checkpoints directly to your shared W&B team space
  group: "mean_teacher"
  job_type: "train"
