defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

# By leaving these empty or omitting the fields, Hydra defaults to your standalone .yaml settings!
model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1